import './globals.css';
import React, { ReactNode } from 'react';

export const metadata: {
  title: string;
  description: string;
} = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body style={{margin:0, padding:0,  textDecoration:'none'}}>{children}</body>
    </html>
  );
}