import Header from "@/components/Header";
import { GlobalContext, GlobalContextProvider, useGlobal } from "../Context";
import "./globals.css";
import { ReactNode } from "react";
import Footer from "@/components/Footer";

export const metadata: {
  title: string;
  description: string;
} = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body style={{ margin: 0, padding: 0, textDecoration: "none" }}>
        <GlobalContextProvider>
          <Header />
          {children}
          <Footer />
        </GlobalContextProvider>
      </body>
    </html>
  );
}
